package com.aosprom.appdownloader

/**
 * Una app de la lista predeterminada.
 * @param packageName ID de paquete en Google Play (ej: com.whatsapp)
 * @param displayName Nombre para mostrar en la lista
 */
data class AppEntry(
    val packageName: String,
    val displayName: String
)

/**
 * Lista predeterminada de apps a instalar.
 * Edita esta lista con los package names de Google Play que quieras.
 */
object PredeterminedApps {
    val list = listOf(
        AppEntry("yqtrack.app", "17TRACK"),
        AppEntry("com.twofasapp", "2FAS Auth"),
        AppEntry("com.addimobile", "Addi"),
        AppEntry("com.alibaba.aliexpresshd", "AliExpress"),
        AppEntry("app.vpn.amtunnelpro", "AM TUNNEL PRO"),
        AppEntry("com.amazon.mShop.android.shopping", "Amazon compras"),
        AppEntry("com.apkmirror.helper.prod", "APKMirror Installer (beta)"),
        AppEntry("com.astropaycard.android", "AstroPay"),
        AppEntry("com.google.android.apps.walletnfcrel", "Billetera de Google"),
        AppEntry("com.intsig.camscanner", "CamScanner"),
        AppEntry("com.rcntv.rcntv", "Canal RCN"),
        AppEntry("com.king.candycrushsaga", "Candy Crush Saga"),
        AppEntry("com.openai.chatgpt", "ChatGPT"),
        AppEntry("co.gov.metromedellin.appCivicanew", "Cívica"),
        AppEntry("com.android.chrome", "Chrome"),
        AppEntry("com.microsoft.copilot", "Copilot"),
        AppEntry("fm.anchor.android", "Spotify for Creators"),
        AppEntry("com.halfbrick.dantheman", "Dan The Man"),
        AppEntry("com.decathlon.app", "Decathlon"),
        AppEntry("com.deepseek.chat", "DeepSeek"),
        AppEntry("com.didiglobal.passenger", "DiDi"),
        AppEntry("com.discord", "Discord"),
        AppEntry("com.disney.disneyplus", "Disney+"),
        AppEntry("com.google.android.apps.docs.editors.docs", "Documentos de Google"),
        AppEntry("com.dolarapp", "DolarApp"),
        AppEntry("com.google.android.apps.docs", "Drive"),
        AppEntry("com.microsoft.appmanager", "Enlace a Windows"),
        AppEntry("com.epidemicsound.player", "Epidemic Sound"),
        AppEntry("com.exito.appcompania", "Exito"),
        AppEntry("com.facebook.katana", "Facebook"),
        AppEntry("com.figma.mirror", "Figma"),
        AppEntry("com.google.android.apps.nbu.files", "Files de Google"),
        AppEntry("com.ionicframework.tabs842240", "Fincomercio"),
        AppEntry("com.google.android.apps.photos", "Fotos"),
        AppEntry("com.google.android.apps.bard", "Gemini"),
        AppEntry("com.google.android.gm", "Gmail"),
        AppEntry("com.google.android.googlequicksearchbox", "Google"),
        AppEntry("ai.x.grok", "Grok"),
        AppEntry("com.hp.printercontrol", "HP"),
        AppEntry("com.spotlightsix.zentimerlite2", "Insight Timer"),
        AppEntry("com.instagram.android", "Instagram"),
        AppEntry("gr.nikolasspyr.integritycheck", "Play Integrity API Check"),
        AppEntry("com.iqor.iqorian", "iQorian"),
        AppEntry("io.github.vvb2060.keyattestation", "Key Attestation Demo"),
        AppEntry("com.gamma.scan", "Lector de código QR"),
        AppEntry("co.littio.app", "Littio"),
        AppEntry("org.localsend.localsend_app", "LocalSend"),
        AppEntry("com.google.android.apps.maps", "Maps"),
        AppEntry("com.google.android.apps.messaging", "Mensajes"),
        AppEntry("com.mercadolibre", "Mercado Libre"),
        AppEntry("com.mercadopago.wallet", "Mercado Pago"),
        AppEntry("com.facebook.orca", "Messenger"),
        AppEntry("co.com.bancolombia.personas.superapp", "Mi Bancolombia"),
        AppEntry("com.xiaomi.wearable", "Mi Fitness"),
        AppEntry("movistar.android.app", "Mi Movistar"),
        AppEntry("com.midatacredito", "Midatacrédito"),
        AppEntry("ai.moises", "Moises"),
        AppEntry("in.krosbits.musicolet", "Musicolet"),
        AppEntry("com.nequi.MobileApp", "Nequi Colombia"),
        AppEntry("com.netflix.mediaclient", "Netflix"),
        AppEntry("com.intcomex.smart", "Nexxt Home"),
        AppEntry("com.nu.production", "Nu"),
        AppEntry("com.microsoft.office.outlook", "Outlook"),
        AppEntry("com.patreon.android", "Patreon"),
        AppEntry("com.king.petrescuesaga", "Pet Rescue Saga"),
        AppEntry("co.picap.passenger", "Picap"),
        AppEntry("com.plip", "PliP"),
        AppEntry("com.amazon.avod.thirdpartyclient", "Prime Video"),
        AppEntry("com.spookyhousestudios.progressbar95", "Progressbar95"),
        AppEntry("com.ProteccionApp", "Protección"),
        AppEntry("com.pco.app.cliente", "Puntos Colombia"),
        AppEntry("co.rapicredit", "Rapicredit"),
        AppEntry("com.google.android.deskclock", "Reloj"),
        AppEntry("com.weberdo.apps.serviceinfo", "Services Info"),
        AppEntry("com.xiaomi.midrop", "ShareMe"),
        AppEntry("com.shazam.android", "Shazam"),
        AppEntry("com.eokoe.smartfitcoach", "Smart Fit"),
        AppEntry("pl.solidexplorer2", "Solid Explorer"),
        AppEntry("com.solventa.app", "Solventa"),
        AppEntry("com.sony.songpal.mdr", "Sound Connect"),
        AppEntry("com.spotify.music", "Spotify"),
        AppEntry("com.suno.android", "Suno"),
        AppEntry("krypton.tbsafetychecker", "TB Checker"),
        AppEntry("org.thunderdog.challegram", "Telegram X"),
        AppEntry("com.einnovation.temu", "Temu"),
        AppEntry("com.instagram.barcelona", "Threads"),
        AppEntry("com.truecaller", "TrueCaller"),
        AppEntry("com.ubercab", "Uber"),
        AppEntry("mark.via.gp", "Via"),
        AppEntry("com.wallpaperscraft.wallpaper", "Wallcraft"),
        AppEntry("wp.wattpad", "Wattpad"),
        AppEntry("com.whatsapp", "WhatsApp"),
        AppEntry("com.twitter.android", "X"),
        AppEntry("cn.xender", "Xender"),
        AppEntry("com.mi.earphone", "Xiaomi Earbuds"),
        AppEntry("ru.zdevs.zarchiver", "ZArchiver"),
        AppEntry("com.htetznaing.zfont2", "zFont 3"),
        AppEntry("air.com.sgn.cookiejam.gp", "Cookie Jam"),
        AppEntry("com.davivienda.daviplataapp", "DaviPlata")
    )
}
